package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// yamlVolume formats a Docker Compose volume mount with proper quoting.
// Paths containing spaces or special characters are safely quoted.
func yamlVolume(indent int, hostPath, containerPath, mode string) string {
	prefix := strings.Repeat(" ", indent)
	vol := fmt.Sprintf("%s:%s", hostPath, containerPath)
	if mode != "" {
		vol = fmt.Sprintf("%s:%s:%s", hostPath, containerPath, mode)
	}
	// Always quote to be safe with special characters
	return fmt.Sprintf("%s- \"%s\"", prefix, vol)
}

type SharedFlags struct {
	Skills    bool
	Workspace bool
	Hooks     bool
}

func parseSharedFlags(args []string) SharedFlags {
	var f SharedFlags
	for _, a := range args {
		switch a {
		case "--shared-skills", "--skills":
			f.Skills = true
		case "--shared-workspace", "--workspace":
			f.Workspace = true
		case "--shared-hooks", "--hooks":
			f.Hooks = true
		case "--shared", "--all":
			f.Skills = true
			f.Workspace = true
		}
	}
	return f
}

func (f SharedFlags) Any() bool {
	return f.Skills || f.Workspace || f.Hooks
}

// writeSharedFlags appends SHARED_* lines to instance.env.
func writeSharedFlags(envFile string, f SharedFlags) error {
	file, err := os.OpenFile(envFile, os.O_APPEND|os.O_WRONLY, credentialFileMode)
	if err != nil {
		return err
	}
	defer file.Close()
	if f.Skills {
		fmt.Fprintln(file, "SHARED_SKILLS=true")
	}
	if f.Workspace {
		fmt.Fprintln(file, "SHARED_WORKSPACE=true")
	}
	if f.Hooks {
		fmt.Fprintln(file, "SHARED_HOOKS=true")
	}
	return nil
}

// readSharedFlags reads SHARED_* from instance.env.
func readSharedFlags(envFile string) SharedFlags {
	return SharedFlags{
		Skills:    readEnvValue(envFile, "SHARED_SKILLS") == "true",
		Workspace: readEnvValue(envFile, "SHARED_WORKSPACE") == "true",
		Hooks:     readEnvValue(envFile, "SHARED_HOOKS") == "true",
	}
}

// setSharedFlag sets or removes a SHARED_* flag in instance.env.
func setSharedFlag(envFile, key string, value bool) error {
	data, err := os.ReadFile(envFile)
	if err != nil {
		return err
	}
	var lines []string
	for _, line := range splitLines(string(data)) {
		if !strings.HasPrefix(line, key+"=") {
			lines = append(lines, line)
		}
	}
	if value {
		lines = append(lines, key+"=true")
	}
	return os.WriteFile(envFile, []byte(strings.Join(lines, "\n")+"\n"), credentialFileMode)
}

// rebuildOverride generates or removes docker-compose.override.yml.
func rebuildOverride(paths Paths, name string) error {
	rt := mustResolveRuntime(paths, name)
	dir := instanceDir(paths, name)
	envFile := filepath.Join(dir, "instance.env")
	overridePath := rt.OverridePath(dir)

	f := readSharedFlags(envFile)
	if !f.Any() {
		os.Remove(overridePath)
		return nil
	}

	var gwVolumes, cliVolumes, gwEnv []string

	if f.Skills {
		os.MkdirAll(filepath.Join(paths.SharedDir, "skills"), 0755)
		mount := yamlVolume(6, filepath.Join(paths.SharedDir, "skills"), rt.MountSkills, "ro")
		gwVolumes = append(gwVolumes, mount)
		cliVolumes = append(cliVolumes, mount)
		if rt.SkillsEnvVar != "" {
			gwEnv = append(gwEnv, fmt.Sprintf("      %s: %s", rt.SkillsEnvVar, rt.MountSkills))
		}
	}
	if f.Workspace {
		os.MkdirAll(filepath.Join(paths.SharedDir, "workspace"), 0755)
		mount := yamlVolume(6, filepath.Join(paths.SharedDir, "workspace"), rt.MountWorkspace, "rw")
		gwVolumes = append(gwVolumes, mount)
		cliVolumes = append(cliVolumes, mount)
	}
	if f.Hooks {
		os.MkdirAll(filepath.Join(paths.SharedDir, "hooks"), 0755)
		mount := yamlVolume(6, filepath.Join(paths.SharedDir, "hooks"), rt.MountHooks, "ro")
		gwVolumes = append(gwVolumes, mount)
		cliVolumes = append(cliVolumes, mount)
	}

	var b strings.Builder
	b.WriteString("# Auto-generated by clawctl — do not edit manually\n")
	b.WriteString("services:\n")
	b.WriteString(fmt.Sprintf("  %s:\n", rt.GatewayService))
	if len(gwEnv) > 0 {
		b.WriteString("    environment:\n")
		for _, e := range gwEnv {
			b.WriteString(e + "\n")
		}
	}
	if len(gwVolumes) > 0 {
		b.WriteString("    volumes:\n")
		for _, v := range gwVolumes {
			b.WriteString(v + "\n")
		}
	}
	if rt.HasCLI() {
		b.WriteString(fmt.Sprintf("  %s:\n", rt.CLIService))
		if len(cliVolumes) > 0 {
			b.WriteString("    volumes:\n")
			for _, v := range cliVolumes {
				b.WriteString(v + "\n")
			}
		}
	}

	return os.WriteFile(overridePath, []byte(b.String()), 0644)
}
