package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

const (
	caddyIncludeDir  = "/etc/caddy/conf.d"
	caddyIncludePath = "/etc/caddy/conf.d/claws.conf"
	caddyfilePath    = "/etc/caddy/Caddyfile"
)

// ---------------------------------------------------------------------------
// claws proxy — reverse proxy management
// ---------------------------------------------------------------------------

func cmdProxy(args []string) error {
	if len(args) < 1 {
		return errorf("usage: claws proxy <setup|reload|status>")
	}
	switch args[0] {
	case "setup":
		return cmdProxySetup(args[1:])
	case "reload":
		return cmdProxyReload(args[1:])
	case "status":
		return cmdProxyStatus(args[1:])
	default:
		return errorf("unknown proxy subcommand: %s", args[0])
	}
}

// proxyInstance holds the info needed to generate a proxy config entry.
type proxyInstance struct {
	Name      string
	Group     string
	Port      string
	Token     string
}

// generateProxyConfig builds the Caddy config string from a list of instances.
func generateProxyConfig(domain, mode string, instances []proxyInstance, includeAuth bool) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by claws proxy — do not edit manually\n")

	if mode == "subdomain" {
		for _, inst := range instances {
			if inst.Port == "" {
				continue
			}
			subdomain := inst.Name
			if inst.Group != "" {
				subdomain = inst.Name + "-" + inst.Group
			}
			b.WriteString(fmt.Sprintf("%s.%s {\n", subdomain, domain))
			if includeAuth && inst.Token != "" {
				b.WriteString(fmt.Sprintf("  @websocket {\n    header Connection *Upgrade*\n    header Upgrade websocket\n  }\n"))
				b.WriteString(fmt.Sprintf("  reverse_proxy @websocket 127.0.0.1:%s {\n", inst.Port))
				b.WriteString(fmt.Sprintf("    header_up Authorization \"Bearer %s\"\n", inst.Token))
				b.WriteString("  }\n")
				b.WriteString(fmt.Sprintf("  reverse_proxy 127.0.0.1:%s {\n", inst.Port))
				b.WriteString(fmt.Sprintf("    header_up Authorization \"Bearer %s\"\n", inst.Token))
				b.WriteString("  }\n")
			} else {
				b.WriteString(fmt.Sprintf("  reverse_proxy 127.0.0.1:%s\n", inst.Port))
			}
			b.WriteString("}\n\n")
		}
	} else {
		b.WriteString(fmt.Sprintf("%s {\n", domain))
		for _, inst := range instances {
			if inst.Port == "" {
				continue
			}
			pathPrefix := "/" + inst.Name
			if inst.Group != "" {
				pathPrefix = "/" + inst.Group + "/" + inst.Name
			}
			b.WriteString(fmt.Sprintf("  handle_path %s/* {\n", pathPrefix))
			if includeAuth && inst.Token != "" {
				b.WriteString(fmt.Sprintf("    reverse_proxy 127.0.0.1:%s {\n", inst.Port))
				b.WriteString(fmt.Sprintf("      header_up Authorization \"Bearer %s\"\n", inst.Token))
				b.WriteString("    }\n")
			} else {
				b.WriteString(fmt.Sprintf("    reverse_proxy 127.0.0.1:%s\n", inst.Port))
			}
			b.WriteString("  }\n")
		}
		b.WriteString("  handle {\n")
		b.WriteString("    respond \"claws proxy — use /<instance> to access\"\n")
		b.WriteString("  }\n")
		b.WriteString("}\n")
	}

	return b.String()
}

// collectProxyInstances reads the registry and collects instance info for proxy config.
func collectProxyInstances(paths Paths) []proxyInstance {
	entries, err := readRegistry(paths)
	if err != nil {
		return nil
	}
	var instances []proxyInstance
	for _, e := range entries {
		ref, _ := ParseRef(e.Name)
		dir := ref.Dir(paths)
		envFile := filepath.Join(dir, "instance.env")
		port := readEnvValue(envFile, "OPENCLAW_GATEWAY_PORT")
		token := readEnvValue(envFile, "OPENCLAW_GATEWAY_TOKEN")
		instances = append(instances, proxyInstance{
			Name:  ref.Name,
			Group: ref.Group,
			Port:  port,
			Token: token,
		})
	}
	return instances
}

func cmdProxySetup(args []string) error {
	paths := resolvePaths()

	var domain string
	mode := "path"
	dryRun := false
	noAuth := false
	for _, a := range args {
		switch {
		case strings.HasPrefix(a, "--domain="):
			domain = a[9:]
		case a == "--subdomain":
			mode = "subdomain"
		case a == "--path":
			mode = "path"
		case a == "--dry-run":
			dryRun = true
		case a == "--no-auth":
			noAuth = true
		}
	}

	if domain == "" {
		return errorf("usage: claws proxy setup --domain=<domain> [--subdomain|--path] [--dry-run] [--no-auth]")
	}

	// Check if Caddy is installed (skip for dry-run)
	if !dryRun {
		if _, err := exec.LookPath("caddy"); err != nil {
			info("Installing Caddy...")
			cmds := [][]string{
				{"apt-get", "install", "-y", "debian-keyring", "debian-archive-keyring", "apt-transport-https", "curl"},
				{"bash", "-c", "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg"},
				{"bash", "-c", "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list"},
				{"apt-get", "update"},
				{"apt-get", "install", "-y", "caddy"},
			}
			for _, c := range cmds {
				cmd := exec.Command("sudo", c...)
				cmd.Stdout = os.Stdout
				cmd.Stderr = os.Stderr
				if err := cmd.Run(); err != nil {
					return errorf("caddy install failed at '%s': %v", strings.Join(c, " "), err)
				}
			}
			info("Caddy installed.")
		} else {
			info("Caddy already installed.")
		}
	}

	instances := collectProxyInstances(paths)
	includeAuth := !noAuth
	config := generateProxyConfig(domain, mode, instances, includeAuth)

	info("Generated Caddy config:")
	fmt.Println()
	fmt.Println(config)

	if dryRun {
		info("(dry run — no files written)")
		return nil
	}

	// Backup existing config if present
	targetPath := caddyIncludePath
	if _, err := os.Stat(targetPath); err == nil {
		backupPath := fmt.Sprintf("%s.bak.%s", targetPath, time.Now().UTC().Format("20060102-150405"))
		if data, err := os.ReadFile(targetPath); err == nil {
			os.WriteFile(backupPath, data, 0644)
			info(fmt.Sprintf("Backed up existing config to %s", backupPath))
		}
	}

	// Ensure include dir exists
	cmd := exec.Command("sudo", "mkdir", "-p", caddyIncludeDir)
	cmd.Run()

	// Write config to include dir
	info(fmt.Sprintf("Writing to %s...", targetPath))
	if err := os.WriteFile(targetPath, []byte(config), 0644); err != nil {
		// Try with sudo
		cmd := exec.Command("sudo", "tee", targetPath)
		cmd.Stdin = strings.NewReader(config)
		cmd.Stdout = nil // suppress tee's stdout echo
		if err := cmd.Run(); err != nil {
			return errorf("failed to write config: %v", err)
		}
	}

	// Ensure main Caddyfile imports the include dir
	ensureCaddyImport()

	// Reload Caddy
	info("Reloading Caddy...")
	cmd = exec.Command("sudo", "systemctl", "reload", "caddy")
	if err := cmd.Run(); err != nil {
		cmd = exec.Command("sudo", "caddy", "reload", "--config", caddyfilePath)
		cmd.Run()
	}

	info("Proxy setup complete.")
	fmt.Println()
	if mode == "subdomain" {
		fmt.Println("  Access instances via:")
		for _, inst := range instances {
			if inst.Port == "" {
				continue
			}
			subdomain := inst.Name
			if inst.Group != "" {
				subdomain = inst.Name + "-" + inst.Group
			}
			fmt.Printf("    https://%s.%s/\n", subdomain, domain)
		}
	} else {
		fmt.Println("  Access instances via:")
		for _, inst := range instances {
			if inst.Port == "" {
				continue
			}
			path := "/" + inst.Name
			if inst.Group != "" {
				path = "/" + inst.Group + "/" + inst.Name
			}
			fmt.Printf("    https://%s%s/\n", domain, path)
		}
	}
	fmt.Println()
	fmt.Println("  Caddy handles HTTPS certificates automatically via Let's Encrypt.")
	fmt.Println("  Ensure port 80 and 443 are open in your firewall.")
	return nil
}

// ensureCaddyImport checks if the main Caddyfile imports conf.d/* and adds the import if missing.
func ensureCaddyImport() {
	importLine := "import /etc/caddy/conf.d/*.conf"
	data, err := os.ReadFile(caddyfilePath)
	if err != nil {
		return // Caddyfile doesn't exist or can't read — Caddy may use conf.d natively
	}
	if strings.Contains(string(data), importLine) {
		return // already has the import
	}
	// Prepend the import line
	newContent := importLine + "\n\n" + string(data)
	if err := os.WriteFile(caddyfilePath, []byte(newContent), 0644); err != nil {
		// Try with sudo
		cmd := exec.Command("sudo", "bash", "-c", fmt.Sprintf("echo '%s\n' | cat - %s > /tmp/caddyfile.tmp && mv /tmp/caddyfile.tmp %s", importLine, caddyfilePath, caddyfilePath))
		cmd.Run()
	}
}

func cmdProxyReload(args []string) error {
	info("Reloading Caddy...")
	cmd := exec.Command("sudo", "systemctl", "reload", "caddy")
	if err := cmd.Run(); err != nil {
		cmd = exec.Command("sudo", "caddy", "reload", "--config", caddyfilePath)
		if err := cmd.Run(); err != nil {
			return errorf("caddy reload failed: %v", err)
		}
	}
	info("Caddy reloaded.")
	return nil
}

func cmdProxyStatus(args []string) error {
	bold := "\033[1m"
	nc := "\033[0m"
	green := "\033[0;32m"
	red := "\033[0;31m"

	fmt.Printf("%sProxy Status%s\n\n", bold, nc)

	// Check Caddy installed
	if _, err := exec.LookPath("caddy"); err == nil {
		fmt.Printf("  Caddy:      %sinstalled%s\n", green, nc)
	} else {
		fmt.Printf("  Caddy:      %snot installed%s\n", red, nc)
		return nil
	}

	// Check Caddy running
	cmd := exec.Command("systemctl", "is-active", "caddy")
	if out, err := cmd.Output(); err == nil && strings.TrimSpace(string(out)) == "active" {
		fmt.Printf("  Service:    %sactive%s\n", green, nc)
	} else {
		fmt.Printf("  Service:    %sinactive%s\n", red, nc)
	}

	// Check config files
	if _, err := os.Stat(caddyIncludePath); err == nil {
		fmt.Printf("  Config:     %s\n", caddyIncludePath)
	} else if _, err := os.Stat(caddyfilePath); err == nil {
		fmt.Printf("  Caddyfile:  %s\n", caddyfilePath)
	} else {
		fmt.Printf("  Config:     %smissing%s\n", red, nc)
	}

	return nil
}
